# Generated by Django 3.1.3 on 2020-12-20 03:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('sdq', django.db.models.manager.Manager()),
            ],
        ),
    ]
